### ISSUE TITLE
gologir.go:202: undefined: http.StatusAlreadyReported

### ISSUE THREAD

**Issue by luisyng** [iomz/golemu#27]
Hi, thank you very much for your work. 

I am trying to install the emulator in Ubuntu. I have successfully installed Go, but when I try to execute: 

```
$ go install
```

I get: 

```
# _/home/luis/go/gologir
./gologir.go:202: undefined: http.StatusAlreadyReported
```

Do you know what could be wrong? Thank you very much.

**Comment by iomz** [comment]
Hello! Thank you for trying this out!

Looks like the dependency is missing. Try:
```shell
$ cd gologir
$ go get ./...
```

or

```
$ go get github.com/iomz/gologir
```
to install all the packages including gologir into your $GOPATH.

**Comment by ktown007** [comment]
I uninstalled the ubuntu package and installed the current build from golang.org/dl

**Comment by Pablini** [comment]
Same problem in Ubuntu LTS 16.04:
ppratsc@QUARKS-V:~$ go get github.com/iomz/gologir
 #github.com/iomz/gologir
gopath/src/github.com/iomz/gologir/golemu.go:218: undefined: http.StatusAlreadyReported

**Comment by iomz** [comment]
This issue was related to go version. Closing it as fixing the web API.
See more in #30
