### ISSUE TITLE
What is tags.csv suppose to look like?

### ISSUE THREAD

**Issue by HanYangZhao** [iomz/golemu#31]
I'm not sure what the content of the tags.csv is suppose to look like. I tried different thing but always end up with some of parsing error. Do you have an example?

**Comment by iomz** [comment]
Hi, just updated the README.md to explain the file to load up the tags to simulate the inventories. `tags.csv` appeared in the help text was wrong, I used to be using CSV for storing the tag data but now the file should be encoded with gob.

See [here](https://github.com/iomz/golemu/blob/master/README.md#llrp-server-modegolemu-server) for the detail. I also fixed some bugs; please use v0.4.1.

**Comment by iomz** [comment]
In addition, I hooked up a huge data set in https://github.com/iomz/docker-gosstrak-demo/releases. dataset.tgz contains a series of gob files for the demo simulation.

**Comment by HanYangZhao** [comment]
thanks for the update, seems to be working now. Another question in the documentation you mentioned
`PC bits: 3000 (indicates a general SGTIN-96 tag)` . What if we're using non-standard tags? Where I can list of available choices for PC bits?

**Comment by iomz** [comment]
To determine valid PC bits for your tags, see Gen2 or ISO/IEC 18000-6C for the Stored PC structure and corresponding tag standards (e.g., TDS or ISO/IEC 15961) for the application family identifiers. 
Chapter 2 of my Master's thesis may be a good summary for you to understand the interrelationship among the standards. https://web.sfc.wide.ad.jp/~iomz/public/mthesis

The least you should have is the length of your data and the GS1 toggle (offset 17h) set to be "non-GS1" if it's a proprietary tag.

I might add more details in README later; however, golemu and go-llrp are only supporting the C1G2PC parameter (no XPC) at the moment.
